[package]
name = "geoarrow-wkb"
version = "0.4.0-beta.1"
authors = ["Kyle Barron <kylebarron2@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/geoarrow/geoarrow-rs"
description = "Rust implementation of GeoArrow"
categories = ["science::geo"]
rust-version = "1.80"

[dependencies]
geo-traits = { workspace = true }

byteorder = "1"
enum-as-inner = "0.6.1"
num_enum = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"

[dev-dependencies]
approx = "0.5.1"
bytes = "1.5.0"
criterion = { version = "0.5", features = ["html_reports"] }

[lib]
doctest = true
