// Auto-generated by cbindgen - DO NOT EDIT
// geoarrow-rs C API

#ifndef GEOARROW_RS_H
#define GEOARROW_RS_H

/* Generated with cbindgen:0.29.4 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <errno.h>
#ifndef ARROW_C_DATA_INTERFACE
#define ARROW_C_DATA_INTERFACE

#define ARROW_FLAG_DICTIONARY_ORDERED 1
#define ARROW_FLAG_NULLABLE 2
#define ARROW_FLAG_MAP_KEYS_SORTED 4

struct ArrowSchema {
  const char* format;
  const char* name;
  const char* metadata;
  int64_t flags;
  int64_t n_children;
  struct ArrowSchema** children;
  struct ArrowSchema* dictionary;
  void (*release)(struct ArrowSchema*);
  void* private_data;
};

struct ArrowArray {
  int64_t length;
  int64_t null_count;
  int64_t offset;
  int64_t n_buffers;
  int64_t n_children;
  const void** buffers;
  struct ArrowArray** children;
  struct ArrowArray* dictionary;
  void (*release)(struct ArrowArray*);
  void* private_data;
};

#endif  // ARROW_C_DATA_INTERFACE

typedef struct ArrowSchema ArrowSchema;
typedef struct ArrowArray ArrowArray;


enum GeoArrowDimensions
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  GEOARROW_DIMENSIONS_UNKNOWN = 0,
  GEOARROW_DIMENSIONS_XY = 1,
  GEOARROW_DIMENSIONS_XYZ = 2,
  GEOARROW_DIMENSIONS_XYM = 3,
  GEOARROW_DIMENSIONS_XYZM = 4,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum GeoArrowDimensions GeoArrowDimensions;
#else
typedef int32_t GeoArrowDimensions;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

enum GeoArrowCoordType
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  GEOARROW_COORD_TYPE_UNKNOWN = 0,
  GEOARROW_COORD_TYPE_SEPARATE = 1,
  GEOARROW_COORD_TYPE_INTERLEAVED = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum GeoArrowCoordType GeoArrowCoordType;
#else
typedef int32_t GeoArrowCoordType;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

enum GeoArrowEdgeType
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  GEOARROW_EDGE_TYPE_PLANAR = 0,
  GEOARROW_EDGE_TYPE_SPHERICAL = 1,
  GEOARROW_EDGE_TYPE_VINCENTY = 2,
  GEOARROW_EDGE_TYPE_THOMAS = 3,
  GEOARROW_EDGE_TYPE_ANDOYER = 4,
  GEOARROW_EDGE_TYPE_KARNEY = 5,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum GeoArrowEdgeType GeoArrowEdgeType;
#else
typedef int32_t GeoArrowEdgeType;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

enum GeoArrowType
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  GEOARROW_TYPE_UNINITIALIZED = 0,
  GEOARROW_TYPE_WKB = 100001,
  GEOARROW_TYPE_LARGE_WKB = 100002,
  GEOARROW_TYPE_WKT = 100003,
  GEOARROW_TYPE_LARGE_WKT = 100004,
  GEOARROW_TYPE_WKB_VIEW = 100005,
  GEOARROW_TYPE_WKT_VIEW = 100006,
  GEOARROW_TYPE_BOX = 990,
  GEOARROW_TYPE_BOX_Z = 1990,
  GEOARROW_TYPE_BOX_M = 2990,
  GEOARROW_TYPE_BOX_ZM = 3990,
  GEOARROW_TYPE_GEOMETRY = 991,
  GEOARROW_TYPE_INTERLEAVED_GEOMETRY = 10991,
  GEOARROW_TYPE_POINT = 1,
  GEOARROW_TYPE_LINESTRING = 2,
  GEOARROW_TYPE_POLYGON = 3,
  GEOARROW_TYPE_MULTIPOINT = 4,
  GEOARROW_TYPE_MULTILINESTRING = 5,
  GEOARROW_TYPE_MULTIPOLYGON = 6,
  GEOARROW_TYPE_GEOMETRYCOLLECTION = 7,
  GEOARROW_TYPE_POINT_Z = 1001,
  GEOARROW_TYPE_LINESTRING_Z = 1002,
  GEOARROW_TYPE_POLYGON_Z = 1003,
  GEOARROW_TYPE_MULTIPOINT_Z = 1004,
  GEOARROW_TYPE_MULTILINESTRING_Z = 1005,
  GEOARROW_TYPE_MULTIPOLYGON_Z = 1006,
  GEOARROW_TYPE_GEOMETRYCOLLECTION_Z = 1007,
  GEOARROW_TYPE_POINT_M = 2001,
  GEOARROW_TYPE_LINESTRING_M = 2002,
  GEOARROW_TYPE_POLYGON_M = 2003,
  GEOARROW_TYPE_MULTIPOINT_M = 2004,
  GEOARROW_TYPE_MULTILINESTRING_M = 2005,
  GEOARROW_TYPE_MULTIPOLYGON_M = 2006,
  GEOARROW_TYPE_GEOMETRYCOLLECTION_M = 2007,
  GEOARROW_TYPE_POINT_ZM = 3001,
  GEOARROW_TYPE_LINESTRING_ZM = 3002,
  GEOARROW_TYPE_POLYGON_ZM = 3003,
  GEOARROW_TYPE_MULTIPOINT_ZM = 3004,
  GEOARROW_TYPE_MULTILINESTRING_ZM = 3005,
  GEOARROW_TYPE_MULTIPOLYGON_ZM = 3006,
  GEOARROW_TYPE_GEOMETRYCOLLECTION_ZM = 3007,
  GEOARROW_TYPE_INTERLEAVED_POINT = 10001,
  GEOARROW_TYPE_INTERLEAVED_LINESTRING = 10002,
  GEOARROW_TYPE_INTERLEAVED_POLYGON = 10003,
  GEOARROW_TYPE_INTERLEAVED_MULTIPOINT = 10004,
  GEOARROW_TYPE_INTERLEAVED_MULTILINESTRING = 10005,
  GEOARROW_TYPE_INTERLEAVED_MULTIPOLYGON = 10006,
  GEOARROW_TYPE_INTERLEAVED_GEOMETRYCOLLECTION = 10007,
  GEOARROW_TYPE_INTERLEAVED_POINT_Z = 11001,
  GEOARROW_TYPE_INTERLEAVED_LINESTRING_Z = 11002,
  GEOARROW_TYPE_INTERLEAVED_POLYGON_Z = 11003,
  GEOARROW_TYPE_INTERLEAVED_MULTIPOINT_Z = 11004,
  GEOARROW_TYPE_INTERLEAVED_MULTILINESTRING_Z = 11005,
  GEOARROW_TYPE_INTERLEAVED_MULTIPOLYGON_Z = 11006,
  GEOARROW_TYPE_INTERLEAVED_GEOMETRYCOLLECTION_Z = 11007,
  GEOARROW_TYPE_INTERLEAVED_POINT_M = 12001,
  GEOARROW_TYPE_INTERLEAVED_LINESTRING_M = 12002,
  GEOARROW_TYPE_INTERLEAVED_POLYGON_M = 12003,
  GEOARROW_TYPE_INTERLEAVED_MULTIPOINT_M = 12004,
  GEOARROW_TYPE_INTERLEAVED_MULTILINESTRING_M = 12005,
  GEOARROW_TYPE_INTERLEAVED_MULTIPOLYGON_M = 12006,
  GEOARROW_TYPE_INTERLEAVED_GEOMETRYCOLLECTION_M = 12007,
  GEOARROW_TYPE_INTERLEAVED_POINT_ZM = 13001,
  GEOARROW_TYPE_INTERLEAVED_LINESTRING_ZM = 13002,
  GEOARROW_TYPE_INTERLEAVED_POLYGON_ZM = 13003,
  GEOARROW_TYPE_INTERLEAVED_MULTIPOINT_ZM = 13004,
  GEOARROW_TYPE_INTERLEAVED_MULTILINESTRING_ZM = 13005,
  GEOARROW_TYPE_INTERLEAVED_MULTIPOLYGON_ZM = 13006,
  GEOARROW_TYPE_INTERLEAVED_GEOMETRYCOLLECTION_ZM = 13007,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum GeoArrowType GeoArrowType;
#else
typedef int32_t GeoArrowType;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Errno-compatible status code. [`GEOARROW_OK`] on success, otherwise one of
 * the values in `<errno.h>`.
 */
typedef int32_t GeoArrowErrorCode;

/**
 * Caller-allocated error sink. Layout-compatible with geoarrow-c's
 * `struct GeoArrowError`, so a consumer of both libraries can pass the same
 * struct to either.
 */
typedef struct GeoArrowError {
  char message[1024];
} GeoArrowError;

/**
 * Reader settings. Every field is optional: zero, or null for the pointers,
 * selects the default.
 */
typedef struct GeoArrowRsGeoParquetReadOptions {
  /**
   * Non-zero to restrict the scan to rows whose bounding box intersects the
   * `bbox_*` rectangle.
   */
  uint8_t has_bbox;
  double bbox_xmin;
  double bbox_ymin;
  double bbox_xmax;
  double bbox_ymax;
  /**
   * Array of `projection_n` NUL-terminated column names to read, or null for
   * every column.
   */
  const char *const *projection_columns;
  uint32_t projection_n;
  /**
   * Array of `row_groups_n` row-group indices to scan, or null for all.
   */
  const uint32_t *row_groups;
  uint32_t row_groups_n;
  /**
   * Rows per batch, or 0 for the parquet default.
   */
  uint64_t batch_size;
  /**
   * Non-zero to parse geometry columns into their native geoarrow type
   * rather than leaving them as `geoarrow.wkb`.
   */
  uint8_t parse_to_native;
  /**
   * Coordinate layout for native parsing, as a
   * [`crate::types::GeoArrowCoordType`]. Read only when `parse_to_native` is
   * set.
   */
  int32_t coord_type;
} GeoArrowRsGeoParquetReadOptions;

/**
 * Writer settings.
 */
typedef struct GeoArrowRsGeoParquetWriteOptions {
  /**
   * 0 writes WKB, which GeoParquet 1.0 readers understand; 1 writes native
   * geoarrow, which needs 1.1.
   */
  uint8_t encoding;
  /**
   * Rows per row group, or 0 for the parquet default.
   */
  uint64_t row_group_size;
  /**
   * NUL-terminated name of the primary geometry column, or null to let the
   * writer choose.
   */
  const char *primary_column;
  /**
   * Non-zero to write bbox covering columns.
   */
  uint8_t generate_covering;
} GeoArrowRsGeoParquetWriteOptions;

#define GEOARROW_OK 0

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * The library version, as a static NUL-terminated string.
 */
const char *GeoArrowRsVersion(void);

/**
 * Release an array written by this library. Null is ignored.
 *
 * # Safety
 * `array` must be null or address an array this library produced and that has
 * not already been released.
 */
void GeoArrowRsArrayRelease(ArrowArray *array);

/**
 * Release a schema written by this library. Null is ignored.
 *
 * # Safety
 * `schema` must be null or address a schema this library produced and that has
 * not already been released.
 */
void GeoArrowRsSchemaRelease(ArrowSchema *schema);

/**
 * Signed area per geometry, in squared CRS units.
 */
GeoArrowErrorCode GeoArrowRsSignedArea(ArrowArray *in_array, ArrowSchema *in_schema, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Unsigned area per geometry, in squared CRS units.
 */
GeoArrowErrorCode GeoArrowRsUnsignedArea(ArrowArray *in_array, ArrowSchema *in_schema, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Sum of segment lengths per geometry, in CRS units.
 */
GeoArrowErrorCode GeoArrowRsEuclideanLength(ArrowArray *in_array, ArrowSchema *in_schema, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Chamberlain-Duquette signed area in m², reading coordinates as lon/lat
 * degrees.
 */
GeoArrowErrorCode GeoArrowRsChamberlainDuquetteSignedArea(ArrowArray *in_array, ArrowSchema *in_schema, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Chamberlain-Duquette unsigned area in m², reading coordinates as lon/lat
 * degrees.
 */
GeoArrowErrorCode GeoArrowRsChamberlainDuquetteUnsignedArea(ArrowArray *in_array, ArrowSchema *in_schema, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Geodesic length in metres, reading coordinates as lon/lat degrees.
 */
GeoArrowErrorCode GeoArrowRsGeodesicLength(ArrowArray *in_array, ArrowSchema *in_schema, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Great-circle length in metres, reading coordinates as lon/lat degrees.
 */
GeoArrowErrorCode GeoArrowRsHaversineLength(ArrowArray *in_array, ArrowSchema *in_schema, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Rhumb-line length in metres, reading coordinates as lon/lat degrees.
 */
GeoArrowErrorCode GeoArrowRsRhumbLength(ArrowArray *in_array, ArrowSchema *in_schema, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Topological dimension per geometry: -1 when empty, otherwise 0, 1 or 2.
 */
GeoArrowErrorCode GeoArrowRsDimensions(ArrowArray *in_array, ArrowSchema *in_schema, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Whether each geometry is empty.
 */
GeoArrowErrorCode GeoArrowRsIsEmpty(ArrowArray *in_array, ArrowSchema *in_schema, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Centroid per geometry, as `geoarrow.point`.
 */
GeoArrowErrorCode GeoArrowRsCentroid(ArrowArray *in_array, ArrowSchema *in_schema, int32_t coord_type, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Convex hull per geometry: `geoarrow.polygon`, or `geoarrow.geometry` when
 * the input encoding has no single dimension.
 */
GeoArrowErrorCode GeoArrowRsConvexHull(ArrowArray *in_array, ArrowSchema *in_schema, int32_t coord_type, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * A point guaranteed to lie inside each geometry, as `geoarrow.point`.
 * Unlike the centroid this never falls outside a concave shape.
 */
GeoArrowErrorCode GeoArrowRsInteriorPoint(ArrowArray *in_array, ArrowSchema *in_schema, int32_t coord_type, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Minimum-area enclosing rectangle per geometry, at any rotation, as
 * `geoarrow.polygon`.
 */
GeoArrowErrorCode GeoArrowRsMinimumRotatedRect(ArrowArray *in_array, ArrowSchema *in_schema, int32_t coord_type, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Axis-aligned bounding rectangle per geometry, as `geoarrow.polygon`.
 */
GeoArrowErrorCode GeoArrowRsBoundingRect(ArrowArray *in_array, ArrowSchema *in_schema, int32_t coord_type, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Midpoint of each geometry's bounding box, as `geoarrow.point`.
 */
GeoArrowErrorCode GeoArrowRsCenter(ArrowArray *in_array, ArrowSchema *in_schema, int32_t coord_type, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Buffer each geometry by `distance`, as `geoarrow.multipolygon`. A negative
 * distance erodes.
 */
GeoArrowErrorCode GeoArrowRsBuffer(ArrowArray *in_array, ArrowSchema *in_schema, double distance, int32_t coord_type, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Concave hull per geometry, as `geoarrow.polygon`. Lower `concavity` follows
 * the input more closely; values at or above 1 approach the convex hull.
 */
GeoArrowErrorCode GeoArrowRsConcaveHull(ArrowArray *in_array, ArrowSchema *in_schema, double concavity, int32_t coord_type, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Point at `fraction` of the way along each line, as `geoarrow.point`.
 * `fraction` is clamped to 0..=1.
 */
GeoArrowErrorCode GeoArrowRsLineInterpolatePoint(ArrowArray *in_array, ArrowSchema *in_schema, double fraction, int32_t coord_type, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Insert vertices so no segment is longer than `max_distance`, measured in CRS
 * units. Output has the input's geometry type.
 */
GeoArrowErrorCode GeoArrowRsDensify(ArrowArray *in_array, ArrowSchema *in_schema, double max_distance, int32_t coord_type, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Chaikin corner-cutting, `iterations` rounds. Output has the input's geometry
 * type.
 */
GeoArrowErrorCode GeoArrowRsChaikinSmoothing(ArrowArray *in_array, ArrowSchema *in_schema, uint32_t iterations, int32_t coord_type, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Rotate each geometry `degrees` counter-clockwise about
 * `(origin_x, origin_y)`. Output has the input's geometry type.
 */
GeoArrowErrorCode GeoArrowRsRotate(ArrowArray *in_array, ArrowSchema *in_schema, double degrees, double origin_x, double origin_y, int32_t coord_type, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Scale each geometry about `(origin_x, origin_y)`. Output has the input's
 * geometry type.
 */
GeoArrowErrorCode GeoArrowRsScale(ArrowArray *in_array, ArrowSchema *in_schema, double x_factor, double y_factor, double origin_x, double origin_y, int32_t coord_type, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Skew each geometry about `(origin_x, origin_y)`. Output has the input's
 * geometry type.
 */
GeoArrowErrorCode GeoArrowRsSkew(ArrowArray *in_array, ArrowSchema *in_schema, double x_degrees, double y_degrees, double origin_x, double origin_y, int32_t coord_type, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Translate each geometry. Output has the input's geometry type.
 */
GeoArrowErrorCode GeoArrowRsTranslate(ArrowArray *in_array, ArrowSchema *in_schema, double x_offset, double y_offset, int32_t coord_type, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Douglas-Peucker simplification. Output has the input's geometry type.
 */
GeoArrowErrorCode GeoArrowRsSimplify(ArrowArray *in_array, ArrowSchema *in_schema, double epsilon, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Visvalingam-Whyatt simplification. Output has the input's geometry type.
 */
GeoArrowErrorCode GeoArrowRsSimplifyVW(ArrowArray *in_array, ArrowSchema *in_schema, double epsilon, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Visvalingam-Whyatt simplification that will not collapse a ring or let an
 * edge cross another. Output has the input's geometry type.
 */
GeoArrowErrorCode GeoArrowRsSimplifyVWPreserve(ArrowArray *in_array, ArrowSchema *in_schema, double epsilon, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Pairwise Euclidean distance in CRS units.
 */
GeoArrowErrorCode GeoArrowRsEuclideanDistance(ArrowArray *left_array, ArrowSchema *left_schema, ArrowArray *right_array, ArrowSchema *right_schema, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Pairwise Hausdorff distance in CRS units.
 */
GeoArrowErrorCode GeoArrowRsHausdorffDistance(ArrowArray *left_array, ArrowSchema *left_schema, ArrowArray *right_array, ArrowSchema *right_schema, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Pairwise Fréchet distance between LineStrings, in CRS units.
 */
GeoArrowErrorCode GeoArrowRsFrechetDistance(ArrowArray *left_array, ArrowSchema *left_schema, ArrowArray *right_array, ArrowSchema *right_schema, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Fraction along each left line, in 0..=1, nearest the paired right point.
 */
GeoArrowErrorCode GeoArrowRsLineLocatePoint(ArrowArray *left_array, ArrowSchema *left_schema, ArrowArray *right_array, ArrowSchema *right_schema, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Pairwise `intersects` predicate.
 */
GeoArrowErrorCode GeoArrowRsIntersects(ArrowArray *left_array, ArrowSchema *left_schema, ArrowArray *right_array, ArrowSchema *right_schema, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Pairwise `contains` predicate.
 */
GeoArrowErrorCode GeoArrowRsContains(ArrowArray *left_array, ArrowSchema *left_schema, ArrowArray *right_array, ArrowSchema *right_schema, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Pairwise DE-9IM predicate. `de9im_pattern` is nine characters drawn from
 * `T F * 0 1 2`, for example `"FT*******"` for `touches`.
 */
GeoArrowErrorCode GeoArrowRsRelateBoolean(ArrowArray *left_array, ArrowSchema *left_schema, ArrowArray *right_array, ArrowSchema *right_schema, const char *de9im_pattern, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Pairwise polygon intersection, as `geoarrow.multipolygon`.
 */
GeoArrowErrorCode GeoArrowRsIntersection(ArrowArray *left_array, ArrowSchema *left_schema, ArrowArray *right_array, ArrowSchema *right_schema, int32_t coord_type, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Pairwise polygon union, as `geoarrow.multipolygon`.
 */
GeoArrowErrorCode GeoArrowRsUnion(ArrowArray *left_array, ArrowSchema *left_schema, ArrowArray *right_array, ArrowSchema *right_schema, int32_t coord_type, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Pairwise polygon difference, left minus right, as `geoarrow.multipolygon`.
 */
GeoArrowErrorCode GeoArrowRsDifference(ArrowArray *left_array, ArrowSchema *left_schema, ArrowArray *right_array, ArrowSchema *right_schema, int32_t coord_type, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Pairwise polygon symmetric difference, as `geoarrow.multipolygon`.
 */
GeoArrowErrorCode GeoArrowRsXor(ArrowArray *left_array, ArrowSchema *left_schema, ArrowArray *right_array, ArrowSchema *right_schema, int32_t coord_type, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Point on each left geometry closest to the paired right query point, as
 * `geoarrow.point`.
 */
GeoArrowErrorCode GeoArrowRsClosestPoint(ArrowArray *left_array, ArrowSchema *left_schema, ArrowArray *right_array, ArrowSchema *right_schema, int32_t coord_type, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Parse a `geoarrow.wkb` array into the native type described by
 * `target_schema`, or into `geoarrow.geometry` when it is null.
 *
 * # Safety
 * The input pair is consumed, `target_schema` is borrowed, and the output pair
 * is written on success.
 */
GeoArrowErrorCode GeoArrowRsFromWKB(ArrowArray *in_array, ArrowSchema *in_schema, const ArrowSchema *target_schema, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Encode a native geoarrow array as `geoarrow.wkb` (i32-offset `Binary`).
 *
 * # Safety
 * The input pair is consumed and the output pair is written on success.
 */
GeoArrowErrorCode GeoArrowRsToWKB(ArrowArray *in_array, ArrowSchema *in_schema, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Parse a `geoarrow.wkt` array into the native type described by
 * `target_schema`, or into `geoarrow.geometry` when it is null.
 *
 * # Safety
 * The input pair is consumed, `target_schema` is borrowed, and the output pair
 * is written on success.
 */
GeoArrowErrorCode GeoArrowRsFromWKT(ArrowArray *in_array, ArrowSchema *in_schema, const ArrowSchema *target_schema, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Encode a native geoarrow array as `geoarrow.wkt` (i32-offset `Utf8`).
 *
 * # Safety
 * The input pair is consumed and the output pair is written on success.
 */
GeoArrowErrorCode GeoArrowRsToWKT(ArrowArray *in_array, ArrowSchema *in_schema, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * # Safety
 * `path` must be a NUL-terminated UTF-8 string, `options` null or readable,
 * and `out_reader` a writable pointer slot. On success the slot receives a
 * handle to release with [`GeoArrowRsGeoParquetReaderClose`].
 */
GeoArrowErrorCode GeoArrowRsGeoParquetReaderOpenPath(const char *path, const struct GeoArrowRsGeoParquetReadOptions *options, void **out_reader, struct GeoArrowError *error);

/**
 * Open a reader over an in-memory parquet file. The bytes are copied, so
 * the caller may free them as soon as this returns.
 *
 * # Safety
 * `bytes` must address `len` readable bytes, or be null when `len` is 0.
 * `options` may be null. `out_reader` must be a writable pointer slot.
 */
GeoArrowErrorCode GeoArrowRsGeoParquetReaderOpenBytes(const uint8_t *bytes, uintptr_t len, const struct GeoArrowRsGeoParquetReadOptions *options, void **out_reader, struct GeoArrowError *error);

/**
 * Write the reader's schema, a struct with one child per column, into
 * `out_schema`. Release it with [`crate::GeoArrowRsSchemaRelease`].
 *
 * # Safety
 * `reader` must be a live handle and `out_schema` a writable, zeroed
 * [`ArrowSchema`].
 */
GeoArrowErrorCode GeoArrowRsGeoParquetReaderSchema(void *reader, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Read the next batch into the output pair.
 *
 * End of stream is reported the way the Arrow C Stream Interface reports
 * it: the call returns [`GEOARROW_OK`] and leaves `out_array->release`
 * null. Check that before using the batch.
 *
 * # Safety
 * `reader` must be a live handle, and the output pair writable and zeroed.
 */
GeoArrowErrorCode GeoArrowRsGeoParquetReaderNext(void *reader, ArrowArray *out_array, ArrowSchema *out_schema, struct GeoArrowError *error);

/**
 * Open a writer over `path`. `schema` describes all columns as a struct,
 * typically taken from [`GeoArrowRsGeoParquetReaderSchema`].
 *
 * # Safety
 * `path` must be NUL-terminated UTF-8, `schema` a readable struct-typed
 * [`ArrowSchema`], `options` null or readable, and `out_writer` a writable
 * pointer slot. On success, finish the writer with
 * [`GeoArrowRsGeoParquetWriterFinish`].
 */
GeoArrowErrorCode GeoArrowRsGeoParquetWriterOpen(const char *path, const ArrowSchema *schema, const struct GeoArrowRsGeoParquetWriteOptions *options, void **out_writer, struct GeoArrowError *error);

/**
 * Encode and append a batch. The input pair is consumed.
 *
 * # Safety
 * `writer` must be a live handle and the input pair a writable,
 * struct-typed Arrow C Data pair.
 */
GeoArrowErrorCode GeoArrowRsGeoParquetWriterPush(void *writer, ArrowArray *in_array, ArrowSchema *in_schema, struct GeoArrowError *error);

/**
 * Release a reader handle. Null is ignored.
 *
 * # Safety
 * `reader` must be null or a handle from an open call that has not been closed.
 */
void GeoArrowRsGeoParquetReaderClose(void *reader);

/**
 * Append the GeoParquet metadata, flush, close the file, and destroy the
 * handle. Null is ignored.
 *
 * # Safety
 * `writer` must be null or a handle from
 * [`GeoArrowRsGeoParquetWriterOpen`] that has not been finished.
 */
GeoArrowErrorCode GeoArrowRsGeoParquetWriterFinish(void *writer, struct GeoArrowError *error);

/**
 * Fill `out` with the Arrow schema for the geoarrow extension type named by
 * `type_`, whose value also selects the dimensions and coordinate layout.
 *
 * On success the schema owns its allocations; release it with
 * [`crate::GeoArrowRsSchemaRelease`].
 *
 * # Safety
 * `out` must address a writable [`ArrowSchema`]. `crs_projjson` must be null
 * or a NUL-terminated UTF-8 PROJJSON string.
 */
GeoArrowErrorCode GeoArrowRsSchemaInit(ArrowSchema *out, int32_t type_, int32_t edge_type, const char *crs_projjson, struct GeoArrowError *error);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* GEOARROW_RS_H */
