//! `geoarrow-expr-geo` kernels exposed over the C ABI.
//!
//! Every function here follows the same contract, so it is stated once rather
//! than repeated on each entry point. Input `ArrowArray`/`ArrowSchema` pairs are
//! consumed: their bytes are moved out and the caller's structs zeroed, so the
//! caller must not release them afterwards. Output pairs are written into
//! caller-allocated slots on success and left untouched on failure. `error` may
//! be null. `coord_type` selects the layout of geometry output and takes a
//! [`crate::types::GeoArrowCoordType`] value.
//!
//! The entry points are generated by one macro per operation shape. The
//! committed header picks them up because cbindgen runs with macro expansion;
//! see the header section of `c/README.md`, and `tests/header_parity.rs` for
//! the guard that keeps the header in step with this file.
#![allow(
    clippy::missing_safety_doc,
    reason = "the shared pointer contract is documented on the module"
)]

use std::ffi::CStr;
use std::os::raw::c_char;
use std::sync::Arc;

use geo::relate::IntersectionMatrix;
use geoarrow_expr_geo as kernel;

use crate::error::{Error, GeoArrowError, GeoArrowErrorCode};
use crate::marshal::{
    Slot, binary_geo_coords, binary_plain, unary_geo, unary_geo_coords, unary_plain,
};
use crate::{ArrowArray, ArrowSchema};

/// One input, a plain Arrow output.
macro_rules! unary_plain_ops {
    ($($(#[$doc:meta])* $c:ident => $body:expr;)*) => {$(
        $(#[$doc])*
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $c(
            in_array: *mut ArrowArray,
            in_schema: *mut ArrowSchema,
            out_array: *mut ArrowArray,
            out_schema: *mut ArrowSchema,
            error: *mut GeoArrowError,
        ) -> GeoArrowErrorCode {
            unsafe {
                unary_plain(
                    Slot::new(in_array, in_schema),
                    Slot::new(out_array, out_schema),
                    error,
                    $body,
                )
            }
        }
    )*};
}

/// Two inputs, a plain Arrow output. An optional scalar parameter group sits
/// between the inputs and the output.
macro_rules! binary_plain_ops {
    ($($(#[$doc:meta])* $c:ident $(($($p:ident: $t:ty),+))? => $body:expr;)*) => {$(
        $(#[$doc])*
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $c(
            left_array: *mut ArrowArray,
            left_schema: *mut ArrowSchema,
            right_array: *mut ArrowArray,
            right_schema: *mut ArrowSchema,
            $($($p: $t,)+)?
            out_array: *mut ArrowArray,
            out_schema: *mut ArrowSchema,
            error: *mut GeoArrowError,
        ) -> GeoArrowErrorCode {
            unsafe {
                binary_plain(
                    Slot::new(left_array, left_schema),
                    Slot::new(right_array, right_schema),
                    Slot::new(out_array, out_schema),
                    error,
                    $body,
                )
            }
        }
    )*};
}

/// One input and scalar parameters, a GeoArrow output in the input's layout.
macro_rules! unary_geo_ops {
    ($($(#[$doc:meta])* $c:ident($($p:ident: $t:ty),*) => $body:expr;)*) => {$(
        $(#[$doc])*
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $c(
            in_array: *mut ArrowArray,
            in_schema: *mut ArrowSchema,
            $($p: $t,)*
            out_array: *mut ArrowArray,
            out_schema: *mut ArrowSchema,
            error: *mut GeoArrowError,
        ) -> GeoArrowErrorCode {
            unsafe {
                unary_geo(
                    Slot::new(in_array, in_schema),
                    Slot::new(out_array, out_schema),
                    error,
                    $body,
                )
            }
        }
    )*};
}

/// One input and scalar parameters, a GeoArrow output in the layout that
/// `coord_type` picks.
macro_rules! unary_geo_coords_ops {
    ($($(#[$doc:meta])* $c:ident($($p:ident: $t:ty),*) => $body:expr;)*) => {$(
        $(#[$doc])*
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $c(
            in_array: *mut ArrowArray,
            in_schema: *mut ArrowSchema,
            $($p: $t,)*
            coord_type: i32,
            out_array: *mut ArrowArray,
            out_schema: *mut ArrowSchema,
            error: *mut GeoArrowError,
        ) -> GeoArrowErrorCode {
            unsafe {
                unary_geo_coords(
                    Slot::new(in_array, in_schema),
                    coord_type,
                    Slot::new(out_array, out_schema),
                    error,
                    $body,
                )
            }
        }
    )*};
}

/// Two inputs, a GeoArrow output in the layout that `coord_type` picks.
macro_rules! binary_geo_coords_ops {
    ($($(#[$doc:meta])* $c:ident => $body:expr;)*) => {$(
        $(#[$doc])*
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $c(
            left_array: *mut ArrowArray,
            left_schema: *mut ArrowSchema,
            right_array: *mut ArrowArray,
            right_schema: *mut ArrowSchema,
            coord_type: i32,
            out_array: *mut ArrowArray,
            out_schema: *mut ArrowSchema,
            error: *mut GeoArrowError,
        ) -> GeoArrowErrorCode {
            unsafe {
                binary_geo_coords(
                    Slot::new(left_array, left_schema),
                    Slot::new(right_array, right_schema),
                    coord_type,
                    Slot::new(out_array, out_schema),
                    error,
                    $body,
                )
            }
        }
    )*};
}

unary_plain_ops! {
    /// Signed area per geometry, in squared CRS units.
    GeoArrowRsSignedArea => |input| Ok(kernel::signed_area(input)?);
    /// Unsigned area per geometry, in squared CRS units.
    GeoArrowRsUnsignedArea => |input| Ok(kernel::unsigned_area(input)?);
    /// Sum of segment lengths per geometry, in CRS units.
    GeoArrowRsEuclideanLength => |input| Ok(kernel::euclidean_length(input)?);
    /// Chamberlain-Duquette signed area in m², reading coordinates as lon/lat
    /// degrees.
    GeoArrowRsChamberlainDuquetteSignedArea =>
        |input| Ok(kernel::chamberlain_duquette_signed_area(input)?);
    /// Chamberlain-Duquette unsigned area in m², reading coordinates as lon/lat
    /// degrees.
    GeoArrowRsChamberlainDuquetteUnsignedArea =>
        |input| Ok(kernel::chamberlain_duquette_unsigned_area(input)?);
    /// Geodesic length in metres, reading coordinates as lon/lat degrees.
    GeoArrowRsGeodesicLength => |input| Ok(kernel::geodesic_length(input)?);
    /// Great-circle length in metres, reading coordinates as lon/lat degrees.
    GeoArrowRsHaversineLength => |input| Ok(kernel::haversine_length(input)?);
    /// Rhumb-line length in metres, reading coordinates as lon/lat degrees.
    GeoArrowRsRhumbLength => |input| Ok(kernel::rhumb_length(input)?);
    /// Topological dimension per geometry: -1 when empty, otherwise 0, 1 or 2.
    GeoArrowRsDimensions => |input| Ok(kernel::dimensions(input)?);
    /// Whether each geometry is empty.
    GeoArrowRsIsEmpty => |input| Ok(kernel::is_empty(input)?);
}

unary_geo_coords_ops! {
    /// Centroid per geometry, as `geoarrow.point`.
    GeoArrowRsCentroid() => |input, coords| Ok(Arc::new(kernel::centroid(input, coords)?));
    /// Convex hull per geometry: `geoarrow.polygon`, or `geoarrow.geometry` when
    /// the input encoding has no single dimension.
    GeoArrowRsConvexHull() => |input, coords| Ok(Arc::new(kernel::convex_hull(input, coords)?));
    /// A point guaranteed to lie inside each geometry, as `geoarrow.point`.
    /// Unlike the centroid this never falls outside a concave shape.
    GeoArrowRsInteriorPoint() =>
        |input, coords| Ok(Arc::new(kernel::interior_point(input, coords)?));
    /// Minimum-area enclosing rectangle per geometry, at any rotation, as
    /// `geoarrow.polygon`.
    GeoArrowRsMinimumRotatedRect() =>
        |input, coords| Ok(Arc::new(kernel::minimum_rotated_rect(input, coords)?));
    /// Axis-aligned bounding rectangle per geometry, as `geoarrow.polygon`.
    GeoArrowRsBoundingRect() =>
        |input, coords| Ok(Arc::new(kernel::bounding_rect(input, coords)?));
    /// Midpoint of each geometry's bounding box, as `geoarrow.point`.
    GeoArrowRsCenter() => |input, coords| Ok(Arc::new(kernel::center(input, coords)?));
    /// Buffer each geometry by `distance`, as `geoarrow.multipolygon`. A negative
    /// distance erodes.
    GeoArrowRsBuffer(distance: f64) =>
        |input, coords| Ok(Arc::new(kernel::buffer(input, distance, coords)?));
    /// Concave hull per geometry, as `geoarrow.polygon`. Lower `concavity` follows
    /// the input more closely; values at or above 1 approach the convex hull.
    GeoArrowRsConcaveHull(concavity: f64) =>
        |input, coords| Ok(Arc::new(kernel::concave_hull(input, concavity, coords)?));
    /// Point at `fraction` of the way along each line, as `geoarrow.point`.
    /// `fraction` is clamped to 0..=1.
    GeoArrowRsLineInterpolatePoint(fraction: f64) =>
        |input, coords| Ok(Arc::new(kernel::line_interpolate_point(input, fraction, coords)?));
    /// Insert vertices so no segment is longer than `max_distance`, measured in CRS
    /// units. Output has the input's geometry type.
    GeoArrowRsDensify(max_distance: f64) =>
        |input, coords| Ok(kernel::densify(input, max_distance, coords)?);
    /// Chaikin corner-cutting, `iterations` rounds. Output has the input's geometry
    /// type.
    GeoArrowRsChaikinSmoothing(iterations: u32) =>
        |input, coords| Ok(kernel::chaikin_smoothing(input, iterations as usize, coords)?);
    /// Rotate each geometry `degrees` counter-clockwise about
    /// `(origin_x, origin_y)`. Output has the input's geometry type.
    GeoArrowRsRotate(degrees: f64, origin_x: f64, origin_y: f64) =>
        |input, coords| Ok(kernel::rotate(input, degrees, origin_x, origin_y, coords)?);
    /// Scale each geometry about `(origin_x, origin_y)`. Output has the input's
    /// geometry type.
    GeoArrowRsScale(x_factor: f64, y_factor: f64, origin_x: f64, origin_y: f64) =>
        |input, coords| Ok(kernel::scale(input, x_factor, y_factor, origin_x, origin_y, coords)?);
    /// Skew each geometry about `(origin_x, origin_y)`. Output has the input's
    /// geometry type.
    GeoArrowRsSkew(x_degrees: f64, y_degrees: f64, origin_x: f64, origin_y: f64) =>
        |input, coords| Ok(kernel::skew(input, x_degrees, y_degrees, origin_x, origin_y, coords)?);
    /// Translate each geometry. Output has the input's geometry type.
    GeoArrowRsTranslate(x_offset: f64, y_offset: f64) =>
        |input, coords| Ok(kernel::translate(input, x_offset, y_offset, coords)?);
}

unary_geo_ops! {
    /// Douglas-Peucker simplification. Output has the input's geometry type.
    GeoArrowRsSimplify(epsilon: f64) => |input| Ok(kernel::simplify(input, epsilon)?);
    /// Visvalingam-Whyatt simplification. Output has the input's geometry type.
    GeoArrowRsSimplifyVW(epsilon: f64) => |input| Ok(kernel::simplify_vw(input, epsilon)?);
    /// Visvalingam-Whyatt simplification that will not collapse a ring or let an
    /// edge cross another. Output has the input's geometry type.
    GeoArrowRsSimplifyVWPreserve(epsilon: f64) =>
        |input| Ok(kernel::simplify_vw_preserve(input, epsilon)?);
}

binary_plain_ops! {
    /// Pairwise Euclidean distance in CRS units.
    GeoArrowRsEuclideanDistance => |left, right| Ok(kernel::euclidean_distance(left, right)?);
    /// Pairwise Hausdorff distance in CRS units.
    GeoArrowRsHausdorffDistance => |left, right| Ok(kernel::hausdorff_distance(left, right)?);
    /// Pairwise Fréchet distance between LineStrings, in CRS units.
    GeoArrowRsFrechetDistance => |left, right| Ok(kernel::frechet_distance(left, right)?);
    /// Fraction along each left line, in 0..=1, nearest the paired right point.
    GeoArrowRsLineLocatePoint => |left, right| Ok(kernel::line_locate_point(left, right)?);
    /// Pairwise `intersects` predicate.
    GeoArrowRsIntersects => |left, right| Ok(kernel::intersects(left, right)?);
    /// Pairwise `contains` predicate.
    GeoArrowRsContains => |left, right| Ok(kernel::contains(left, right)?);
    /// Pairwise DE-9IM predicate. `de9im_pattern` is nine characters drawn from
    /// `T F * 0 1 2`, for example `"FT*******"` for `touches`.
    GeoArrowRsRelateBoolean(de9im_pattern: *const c_char) => |left, right| {
        let pattern = de9im_pattern_from(de9im_pattern)?;
        let matches = move |m: IntersectionMatrix| m.matches(&pattern).unwrap_or(false);
        Ok(kernel::relate_boolean(left, right, matches)?)
    };
}

binary_geo_coords_ops! {
    /// Pairwise polygon intersection, as `geoarrow.multipolygon`.
    GeoArrowRsIntersection =>
        |left, right, coords| Ok(Arc::new(kernel::intersection(left, right, coords)?));
    /// Pairwise polygon union, as `geoarrow.multipolygon`.
    GeoArrowRsUnion => |left, right, coords| Ok(Arc::new(kernel::union(left, right, coords)?));
    /// Pairwise polygon difference, left minus right, as `geoarrow.multipolygon`.
    GeoArrowRsDifference =>
        |left, right, coords| Ok(Arc::new(kernel::difference(left, right, coords)?));
    /// Pairwise polygon symmetric difference, as `geoarrow.multipolygon`.
    GeoArrowRsXor => |left, right, coords| Ok(Arc::new(kernel::xor(left, right, coords)?));
    /// Point on each left geometry closest to the paired right query point, as
    /// `geoarrow.point`.
    GeoArrowRsClosestPoint =>
        |left, right, coords| Ok(Arc::new(kernel::closest_point(left, right, coords)?));
}

/// # Safety
/// `pattern` must be null or a NUL-terminated string.
unsafe fn de9im_pattern_from(pattern: *const c_char) -> Result<String, Error> {
    if pattern.is_null() {
        return Err(Error::invalid("de9im_pattern is null"));
    }
    let pattern = unsafe { CStr::from_ptr(pattern) }
        .to_str()
        .map_err(|e| Error::invalid(format!("de9im_pattern is not valid UTF-8: {e}")))?;
    if pattern.len() != 9 {
        return Err(Error::invalid(format!(
            "de9im_pattern must be 9 characters, got {} ({pattern:?})",
            pattern.len()
        )));
    }
    if let Some(c) = pattern.chars().find(|c| !"TtFf*012".contains(*c)) {
        return Err(Error::invalid(format!(
            "de9im_pattern contains {c:?}; allowed characters are T F * 0 1 2"
        )));
    }
    Ok(pattern.to_owned())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::error::EINVAL;

    #[test]
    fn rejects_malformed_de9im_patterns() {
        for pattern in ["", "T*T*****", "T*T*******", "T*T****X*", "ZZZZZZZZZ"] {
            let c = std::ffi::CString::new(pattern).unwrap();
            let err = unsafe { de9im_pattern_from(c.as_ptr()) }.unwrap_err();
            assert_eq!(err.code, EINVAL, "for {pattern:?}");
        }
        assert!(unsafe { de9im_pattern_from(std::ptr::null()) }.is_err());
    }

    #[test]
    fn accepts_well_formed_de9im_patterns() {
        for pattern in ["T*T******", "FT*******", "012*TtFf*"] {
            let c = std::ffi::CString::new(pattern).unwrap();
            assert_eq!(unsafe { de9im_pattern_from(c.as_ptr()) }.unwrap(), pattern);
        }
    }
}
