class Area:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Distance:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Length:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...
