class IsValid:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class IsValidReason:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...
