[package]
name = "pyo3-geoarrow"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "GeoArrow integration for pyo3."
readme = "README.md"
repository = { workspace = true }
license = { workspace = true }
keywords = ["python", "arrow"]
categories = []
rust-version = { workspace = true }

[features]
default = ["geozero", "geojson"]
geozero = ["dep:geozero", "geoarrow-array/geozero"]

[dependencies]
arrow-array = { workspace = true }
arrow-buffer = { workspace = true }
arrow-cast = { workspace = true }
arrow-schema = { workspace = true }
geo-traits = { workspace = true }
geo-types = { workspace = true }
geoarrow-array = { workspace = true }
geoarrow-cast = { workspace = true }
geoarrow-schema = { workspace = true }
geoarrow-expr-geo = { workspace = true }
geojson = { workspace = true, optional = true }
geozero = { workspace = true, optional = true }
pyo3 = { workspace = true, features = ["chrono", "indexmap"] }
pyo3-arrow = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }

[lib]
crate-type = ["rlib"]

[package.metadata.docs.rs]
all-features = true
