[workspace]
members = ["geoarrow-compute", "geoarrow-core", "geoarrow-io", "pyo3-geoarrow"]
resolver = "2"

[workspace.package]
authors = ["Kyle Barron <kylebarron2@gmail.com>"]
version = "0.3.0"
edition = "2021"
homepage = "https://geoarrow.org/geoarrow-rs/"
repository = "https://github.com/geoarrow/geoarrow-rs"
license = "MIT OR Apache-2.0"
keywords = ["python", "arrow", "geospatial"]
categories = ["wasm", "science::geo"]
rust-version = "1.80"

[workspace.dependencies]
arrow = "53"
arrow-array = "53"
arrow-buffer = "53"
arrow-schema = "53"
geoarrow = { path = "../", features = ["geozero"] }
geozero = "0.13"
indexmap = "2.5.0"
pyo3 = { version = "0.21.0", features = [
    "abi3-py38",
    "hashbrown",
    "serde",
    "anyhow",
] }
pyo3-arrow = { git = "https://github.com/kylebarron/arro3", rev = "142c2cd" }
serde_json = "1"
thiserror = "1"
