[workspace]
members = ["geoarrow-compute", "geoarrow-core", "geoarrow-io", "pyo3-geoarrow"]
resolver = "2"

[workspace.package]
authors = ["Kyle Barron <kylebarron2@gmail.com>"]
version = "0.4.0-beta.4"
edition = "2024"
homepage = "https://geoarrow.org/geoarrow-rs/"
repository = "https://github.com/geoarrow/geoarrow-rs"
license = "MIT OR Apache-2.0"
keywords = ["python", "arrow", "geospatial"]
categories = ["wasm", "science::geo"]
rust-version = "1.85"

[workspace.dependencies]
arrow = "55"
arrow-array = "55"
arrow-buffer = "55"
arrow-schema = "55"
geo-traits = "0.2"
geoarrow = { path = "../rust/geoarrow" }
geoarrow-array = { path = "../rust/geoarrow-array" }
geoarrow-cast = { path = "../rust/geoarrow-cast" }
geoarrow-flatgeobuf = { path = "../rust/geoarrow-flatgeobuf" }
geoarrow-geoparquet = { path = "../rust/geoarrow-geoparquet" }
geoarrow-schema = { path = "../rust/geoarrow-schema" }
geozero = "0.14"
indexmap = "2.5.0"
numpy = "0.24"
object_store = "0.12"
parquet = "55"
pyo3 = { version = "0.24", features = ["hashbrown", "serde", "anyhow"] }
pyo3-arrow = "0.9"
pyo3-geoarrow = { path = "./pyo3-geoarrow" }
serde_json = "1"
thiserror = "1"
