__all__ = [
    "Box2D",
    "Box3D",
    "XMin",
    "YMin",
    "ZMin",
    "XMax",
    "YMax",
    "ZMax",
    "MakeBox2D",
    "MakeBox3D",
]

class Box2D:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Box3D:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class XMin:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class YMin:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class ZMin:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class XMax:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class YMax:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class ZMax:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class MakeBox2D:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class MakeBox3D:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...
