[project]
name = "docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.uv]
dev-dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material[imaging]>=9.5.40",
    "pymdown-extensions>=10.11.2",
]
