[package]
name = "geodatafusion-geojson"
version = "0.1.0-dev"
authors = ["Kyle Barron <kylebarron2@gmail.com>"]
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "GeoJSON TableProvider for DataFusion"
categories = { workspace = true }
rust-version = { workspace = true }

[dependencies]
arrow-schema = { workspace = true }
async-trait = { workspace = true }
datafusion = { workspace = true }
datafusion-datasource = { workspace = true }
geoarrow-geojson = { workspace = true }
object_store = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
arrow-array = { workspace = true }
geo-traits = { workspace = true }
geoarrow-array = { workspace = true, features = ["test-data"] }
geoarrow-schema = { workspace = true }
geodatafusion = { workspace = true }
geojson = { workspace = true }
object_store = { workspace = true, features = ["http"] }
serde_json = "1.0"
tokio = { workspace = true, features = ["macros", "fs", "rt-multi-thread"] }
wkt = { workspace = true }

[package.metadata.docs.rs]
all-features = true
