from typing import Literal

class GeoHash:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class PointFromGeoHash:
    def __init__(
        self,
        *,
        coord_type: Literal["interleaved", "separated"] | None = None,
    ) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Box2DFromGeoHash:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...
