name: Publish Python docs via GitHub Pages

# Only run on new tags starting with `py-v`
on:
  push:
    tags:
      - "py-v*"
  workflow_dispatch:

# https://stackoverflow.com/a/77412363
permissions:
  contents: write
  pages: write

jobs:
  build:
    name: Deploy Python docs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@v4
        # We need to additionally fetch the gh-pages branch for mike deploy
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Set up Python 3.11
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install a specific version of uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          version: "0.4.x"

      - name: Build python package
        run: |
          uv run maturin develop -m geoarrow-core/Cargo.toml
          uv run maturin develop -m geoarrow-compute/Cargo.toml
          uv run maturin develop -m geoarrow-io/Cargo.toml

      - name: Deploy docs
        env:
          GIT_COMMITTER_NAME: CI
          GIT_COMMITTER_EMAIL: ci-bot@example.com
        run: |
          # Get most recent git tag
          # https://stackoverflow.com/a/7261049
          # https://stackoverflow.com/a/3867811
          # We don't use {{github.ref_name}} because if triggered manually, it
          # will be a branch name instead of a tag version.
          # Then remove `py-` from the tag
          VERSION=$(git describe --tags --match="py-*" --abbrev=0 | cut -c 4-)

          # Only publish docs as latest version if no letters in git tag
          # after the first character
          # (usually the git tag will have v as the first character)
          # Note the `cut` index is 1-ordered
          if echo $VERSION | cut -c 2- | grep -q "[A-Za-z]"; then
            echo "Is beta version"
            echo "Version is $VERSION"
            # For beta versions publish but don't set as latest
            uv run mike deploy $VERSION --update-aliases --push --deploy-prefix python/
          else
            echo "Is NOT beta version"
            echo "Version is $VERSION"
            uv run mike deploy $VERSION latest --update-aliases --push --deploy-prefix python/
          fi
