name: Publish to crates.io
on:
  push:
    # Triggers when pushing tags starting with 'rust-v'
    tags: ["rust-v*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: rust-release
    permissions:
      id-token: write # Required for OIDC token exchange
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: "recursive"
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: prefix-dev/setup-pixi@v0.9.5
        with:
          activate-environment: true
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          manifest-path: build/pixi.toml
      - name: Tweak environment to find GDAL
        run: |
          echo "PKG_CONFIG_PATH=$(pwd)/build/.pixi/envs/default/lib/pkgconfig" >> "$GITHUB_ENV"
          echo "LD_LIBRARY_PATH=$(pwd)/build/.pixi/envs/default/lib" >> "$GITHUB_ENV"
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
